version: '3.4'

services:
  bluebank.accounts.api:
    image: ${DOCKER_REGISTRY-}bluebankaccountsapi
    build:
      context: .
      dockerfile: BlueBank.Accounts/BlueBank.Accounts.Api/Dockerfile

  bluebank.apigateway:
    image: ${DOCKER_REGISTRY-}bluebankapigateway
    build:
      context: .
      dockerfile: BlueBank.ApiGateway/Dockerfile