name: API Gateway - Build and Create Docker Image.

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - src/BlueBank/BlueBank.ApiGateway/**
    - .github/workflows/api-gateway.yml
  pull_request:
    branches: [ main ]
    paths:
    - src/BlueBank/BlueBank.ApiGateway/**
    - .github/workflows/api-gateway.yml

defaults:
   run:
    working-directory: ./src/BlueBank/BlueBank.ApiGateway/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build the Docker image
      run: docker build . --file BlueBank.ApiGateway/Dockerfile --tag bluebank-api:$(date +%s)
      working-directory: ./src/BlueBank/
