name: Publish Packages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - src/BlueBank/**
    - .github/workflows/shared-kernal.yml
  pull_request:
    branches: [ main ]
    paths:
    - src/BlueBank/**
    - .github/workflows/shared-kernal.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
	  working-directory: ./src/BlueBank/BlueBank.SharedKernel
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish BlueBank.SharedKernel
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/BlueBank/BlueBank.SharedKernel/BlueBank.SharedKernel.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
