name: Publish Shared Kernel

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - src/BlueBank/BlueBank.SharedKernel/**
    - .github/workflows/shared-kernal.yml
  pull_request:
    branches: [ main ]
    paths:
    - src/BlueBank/BlueBank.SharedKernel/**
    - .github/workflows/shared-kernal.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src/BlueBank/BlueBank.SharedKernel
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src/BlueBank/BlueBank.SharedKernel
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./src/BlueBank/BlueBank.SharedKernel
    - name: Pack
      run: dotnet pack --no-build --configuration Release src/BlueBank/BlueBank.SharedKernel/BlueBank.SharedKernel.csproj --output .
    - name: PushGithub
      run: dotnet nuget push *.nupkg --no-symbols --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
